language: c
services:
  - docker
# set up
before_install:
  - sudo apt-get update
  - sudo apt-get install -y realpath
# command to run build.
script: 
  # Debian package build
  - >
      sh -ex ./mkdeb.sh
      --docker
      --docker-image sjlongland/debian-pkg-build-env:latest
  # Ubuntu package build
  - >
      sh -ex ./mkdeb.sh
      --docker
      --docker-image sjlongland/debian-pkg-build-env:latest
      --recycle-orig
