language: c
dist: xenial
services:
  - docker
# decryption of secrets
before_install:
  - openssl aes-256-cbc -K $encrypted_f6a0b98cfb34_key -iv $encrypted_f6a0b98cfb34_iv -in .travis-secret.tar.enc -out .travis-secret.tar -d
# command to run build.
script: 
  # Debian package build
  - >
      sh -ex ./mkdeb.sh
      --docker
      --docker-image sjlongland/debian-pkg-build-env:latest
  # Ubuntu package build
  - >
      sh -ex ./mkdeb.sh
      --docker
      --docker-image sjlongland/debian-pkg-build-env:latest
      --recycle-orig
  # Prepare .ssh directory
  - tar -C ~ -xf .travis-secret.tar
  - chmod 0700 ~/.ssh
  # Upload the built packages
  - >
      (
        echo "cd ${UPLOAD_DIR}";
        find dist -type f | while read file; do
          echo "put ${file}";
        done
      ) | sftp -i ~/.ssh/id_rsa \
          -P ${UPLOAD_PORT} ${UPLOAD_USER}@${UPLOAD_HOST}
env:
  global:
    secure: "iA8027zvLwm5jAkupGwuj/ryhA6EdzndtVosVnmCE+8VGb+0fwzd1shZ3NOqNf8dCZB0pLKLNZSYSHh7QU7TmJAMLpww06BbCOl1q1ZtHH1HgNOC6JiyESsvUz5EK3qTQWXJdMvYnU/kdYUIHaaflqZz/gEZiavQmYqMg5roQrCTUL0UUwcpepevvmeE2g+/uYd27lvdn145+TmWwHcFgfyyCj3U+fMGUAndKPCoEDQ7Vxs9FSm5PWZbJyCTNZBi7e5xYGAId6vun5Cc7gOJUKdpfSxmY7HZdh7hxTcw/ODB7oUy/rPiL0Z5aFgCRQL8hkZKTpWG5gPE1IwSX5qWeGK3q3ROwEw+ZEJz32WK9kcC5ly0Sq/6qLxpxNrB95T2ik35xx2iFEkMcDOKzyyrKuJELrMpZ5VT+CYs9cOrC/oeUEHrkpz+3j5iNNMo0tRdUIfOh9z9OuPyJWD/DdbLfy9n9q0ppp9App9pft+bwFPYZHs3+XbBL+wqjxYL2J58RzRHTTp+lpqBUXiTYNvtDElOjoOrUdmqCqNm2P1GNNjZHAkjLUs4++F92g59k3QxKZ/GL9ErQkKX2QSHayu9+oDCbiRU1Ms6ZZSn1EUwcgfU+Ee059SEFMrUwV1MwJVVYzPvR6rJOgPbYKBLlliEWEgoTALCSU8f9IycIN1VDko="
