language: c
dist: xenial
services:
  - docker
# decryption of secrets
before_install:
  - openssl aes-256-cbc -K $encrypted_f6a0b98cfb34_key -iv $encrypted_f6a0b98cfb34_iv -in .travis-secret.tar.enc -out .travis-secret.tar -d
# command to run build.
script: 
  # Debian package build
  - >
      sh -ex ./mkdeb.sh
      --docker
      --docker-image sjlongland/debian-pkg-build-env:latest
  # Ubuntu package build
  - >
      sh -ex ./mkdeb.sh
      --docker
      --docker-image sjlongland/debian-pkg-build-env:latest-ubuntu
      --recycle-orig
  # Prepare .ssh directory
  - tar -C ~ -xf .travis-secret.tar
  - chmod 0700 ~/.ssh
  # Upload the built packages
  - >
      (
        echo "cd ${UPLOAD_DIR}";
        find dist -type f | while read file; do
          echo "put ${file}";
        done
      ) | sftp -q ${UPLOAD_USER}@${UPLOAD_HOST}
env:
  global:
    secure: "V5k1y1aEsvJGbAwsIJR0a+y/oHuYxO8lQmTeANJVwcoX8BvuQ7OZpbtO507DRmKqt0mwtdtoEIO2uDSDbKmv1moXWxwIinqkwtbMl99NA1kTQjTNphFKmEY0qgnwcpbwGzggYpjkjhUzOklALbzBwEdglHlLiLc6qalwxYO03xHplRRMx6BAAxMR0K4zHNFs8sIqTDTduFvwTDOJqiptcXlT9+OKg3dMtsIJhdnt6c2mYN5iAmZ9Xs463C2wzavOmdr6LlMdxZ3e7uEDxwklp3UXUuVtOMYIeJuJT+F5w+r/YGar+TPKa4gYsG8MzBRDD/55hUedHW8yCqJIPMVL+8iuCG+EgizLWES8oFSn73nRnGVRxZXNIQASdRrP8Zl1C1qlA6YfDLyRQcBNp1waJhDhufTwYCeY5EPeofBvhvSbm5r/Vy1mmxwztctoolcxNk6SRyHtmwWX1mzcP5Hl/PPY415rwAS84xYRgmEeRZ2t+sKwaATDtTPACl1lyS7EBC+sTseqK9iLUqgXcLlPI1qwYlq0LDPQCvclapLlAiiwZQLkRboP4vqXZNKHlVioQZL+aWTce3CgwW1HWoL7cDl4Z/wejo2mHetc3EwZOtvyeb/CJL3BEYhs6gRjl9fYfijtBrG3hCGMRNK33sj3AEpYuQOH671Bexx8gJIEKAg="
